version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "submodule"
    directory: "/"
    schedule:
      interval: "daily"
