version = 1

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/ss-o/i"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true