version: "3.8"

services:
  i-get:
    build: .
#    image: ghcr.io/ss-o/i:latest
    container_name: i-get
    restart: always
    ports:
      - "3000:3000"
#    environment:
#      USER: yourgithubuser
#      GH_TOKEN: yourgithubtoken
