version: "3.8"

services:
  i-get:
    build: .
    container_name: i-get
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - USER
      - PORT
      - HTTP_HOST
      - FORCE_REPO
      - FORCE_USER
      - GITHUB_TOKEN
