on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

name: Release CI

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      #      - name: Import GPG key
      #        id: import_gpg
      #        uses: crazy-max/ghaction-import-gpg@v4
      #        with:
      #          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Build release
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --config .github/goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        if: success()
